//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GxWebClient.GxServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GxServiceReference.HBServiceSoap")]
    public interface HBServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryObject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryObject(string xtlb, string jkid, string xmlDoc, string yhdh, string mm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WriteObject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WriteObject(string xtlb, string jkid, string xmlDoc, string yhdh, string mm);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HBServiceSoapChannel : GxWebClient.GxServiceReference.HBServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HBServiceSoapClient : System.ServiceModel.ClientBase<GxWebClient.GxServiceReference.HBServiceSoap>, GxWebClient.GxServiceReference.HBServiceSoap {
        
        public HBServiceSoapClient() {
        }
        
        public HBServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HBServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HBServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HBServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }

        public string QueryObject(string xtlb, string jkid, string xmlDoc, string yhdh, string mm) {
            ini.INIIO.saveSocketLogInf("【QueryObject】" + "[xtlb=" + xtlb + "]" + "[jkid=" + jkid + "]" + "[xmlDoc=...]" + "[yhdh=" + yhdh + "]" + "[mm=" + mm + "]");
            return base.Channel.QueryObject(xtlb, jkid, xmlDoc, yhdh, mm);
        }
        
        public string WriteObject(string xtlb, string jkid, string xmlDoc, string yhdh, string mm) {
            ini.INIIO.saveSocketLogInf("【WriteObject】" + "[xtlb=" + xtlb + "]" + "[jkid=" + jkid + "]" + "[xmlDoc=...]" + "[yhdh=" + yhdh + "]" + "[mm=" + mm + "]");
            return base.Channel.WriteObject(xtlb, jkid, xmlDoc, yhdh, mm);
        }
    }
}
